services:
  dapr-placement:
    container_name: dapr-placement
    image: "daprio/dapr:latest"
    command: [
        "./placement", 
        "-port", 
        "50000", 
        "-log-level", 
        "debug"]
    ports:
      - "50000:50000"

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  chatbotapi:
    container_name: chatbotapi
    image: ${DOCKER_REGISTRY-}chatbotapi
    build:
      context: .
      dockerfile: ChatBotApi/Dockerfile

  chatbotapi-dapr:
    container_name: chatbotapi-dapr
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "chatbotapi",
        "-app-port",
        "8080",
        "-dapr-http-port",
        "3500",
        "-placement-host-address",
        "dapr-placement:50000",
        "-components-path",
        "components",
        "-config",
        "configuration/config.yaml",
      ]
    network_mode: "service:chatbotapi"
    volumes:
      - "./ChatBotApi/dapr/local/components:/components"
      - "./ChatBotApi/dapr/local/configuration:/configuration"
    depends_on:
        - dapr-placement
        - redis
        - chatbotapi
  